[devshell]
name = "Hades"
motd = "{202}🔨 Welcome to Hades{reset}\n$(type -p menu &>/dev/null && menu)\n"
packages = [ "alejandra"
           , "nodePackages.prettier"
           , "shfmt"
           , "editorconfig-checker"
           , "nodejs"
           , "nodePackages.pnpm"
]

[[commands]]
package = "treefmt"

# TODO: Add rush to nixpkgs
# [[commands]]
# package = "nodePackages.rush"
# category = "package management"

[[commands]]
name = "bld"
command = 'rush build "$@"'
help = "Build projects incrementally."
category = "monorepo"

[[commands]]
name = "upd"
command = 'rush update "$@"'
help = "Update."
category = "monorepo"

[[commands]]
name = "rbld"
command = "upd --purge && rush rebuild"
help = "Purge and update. Rebuild all projects."
category = "monorepo"
