packages:
  - bots/*
  - apps/*
  - libs/*
  - rigs/*

catalog:
  '@ldlework/inversify-config-injection': 0.0.8
  '@types/node': ^24.0.3
  discord.js: 14.20.0
  inversify: 6.2.2
  reflect-metadata: ~0.2.2
  tsup: ^8.5.0
  turbo: 2.5.4
  typescript: ~5.8.3
  pkgroll: 2.13.1

linkWorkspacePackages: true
