packages:
  - bots/*
  - apps/*
  - libs/*
  - rigs/*
  - pkgs/*

catalog:
  '@ldlework/inversify-config-injection': 0.1.3
  '@ldlework/categoric-containers': 0.1.6
  '@ldlework/categoric-decorators': 1.0.1
  '@ldlework/inversify-binding-decorators': 4.0.2
  '@types/node': 24.0.3
  discord.js: 14.20.0
  inversify: 7.5.4
  reflect-metadata: 0.2.2
  turbo: 2.5.4
  typescript: ~5.8.3
  pkgroll: 2.13.1
  tsx: 4.20.3
  rimraf: 6.0.1
  '@biomejs/biome': ^2.0.6

catalogMode: strict

linkWorkspacePackages: true

patchedDependencies:
  undici@6.21.3: patches/undici@6.21.3.patch
  '@discordjs/ws@1.2.3': patches/@discordjs__ws@1.2.3.patch
  '@docusaurus/plugin-content-docs': patches/@docusaurus__plugin-content-docs.patch

strictPeerDependencies: true
