@startuml

skinparam sequenceArrowThickness 2
skinparam roundcorner 20
skinparam ClassBorderColor Black
skinparam ClassBackgroundColor White
skinparam Padding 10
skinparam HeaderFontSize 60
skinparam linetype ortho

skinparam ClassBackgroundColor<<C>> lightgreen
skinparam ClassBackgroundColor<<B>> lightblue
skinparam ClassBackgroundColor<<M>> lightpink

hide members
hide circle
hide stereotype

header
        Karma Architecture
endheader

class ReactionService { }

ReactionService o-up-> DiscordClient

CommandService o-up-> DiscordClient
CommandService o-left-> ReactionService

ReactionService o--> DataService
@enduml
