name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [lts/*, latest]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Turbo Cache
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm install
      - name: Build
        run: pnpm run build
      - name: Biome Check
        run: pnpm run ci:biome
      # Deploy docs to hades-ts.github.io
      - name: Deploy Docs
        if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'pull_request'
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY_PRIVATE }}
          publish_dir: ./apps/docs/build
          external_repository: hades-ts/hades-ts.github.io
          publish_branch: main
          enable_jekyll: false
      
      # Deploy log viewer to hades-logs.github.io
      - name: Deploy Log Viewer
        if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'pull_request'
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY_LOGS_PRIVATE }}
          publish_dir: ./apps/log-viewer/dist
          external_repository: hades-ts/hades-logs.github.io
          publish_branch: main
          enable_jekyll: false
