name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [lts/*, latest]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Turbo Cache
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm install
      - name: Build
        run: pnpm run build
      # - name: Biome Check
      #   run: pnpm run ci:biome
      - name: Check build outputs
        if: matrix.node-version == 'lts/*'
        run: |
          echo "Checking build outputs..."
          ls -la ./apps/docs/ || echo "docs directory not found"
          ls -la ./apps/docs/build/ || echo "docs build directory not found"
          ls -la ./apps/log-viewer/ || echo "log-viewer directory not found"
          ls -la ./apps/log-viewer/dist/ || echo "log-viewer dist directory not found"
      - name: Upload docs build artifacts
        if: matrix.node-version == 'lts/*'
        uses: actions/upload-artifact@v4
        with:
          name: docs-build
          path: ./apps/docs/build
          retention-days: 1
          if-no-files-found: error
      - name: Upload log-viewer build artifacts
        if: matrix.node-version == 'lts/*'
        uses: actions/upload-artifact@v4
        with:
          name: log-viewer-build
          path: ./apps/log-viewer/dist
          retention-days: 1
          if-no-files-found: error
