name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      # - name: Verify Change Logs
      #   run: node common/scripts/install-run-rush.js change --verify
      - name: Rush Update
        run: node common/scripts/install-run-rush.js update
      - name: Rush rebuild
        run: node common/scripts/install-run-rush.js rebuild
      # take apps/docs/build as github pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY_PRIVATE }}
          publish_dir: ./apps/docs/build
          external_repository: hades-ts/hades-ts.github.io
          publish_branch: main
          enable_jekyll: false