name: Deploy Docs
on:
  workflow_run:
    workflows: [CI]
    types:
      - completed

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push' && github.event.workflow_run.head_branch == 'main' }}
    steps:
      - name: Show workflow run info
        run: |
          echo "Workflow run ID: ${{ github.event.workflow_run.id }}"
          echo "Workflow run conclusion: ${{ github.event.workflow_run.conclusion }}"
          echo "Workflow run event: ${{ github.event.workflow_run.event }}"
          echo "Workflow run head branch: ${{ github.event.workflow_run.head_branch }}"
          echo "Workflow run head SHA: ${{ github.event.workflow_run.head_sha }}"
      - name: Download docs build artifacts
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: ci.yml
          name: docs-build
          path: ./apps/docs/build
          run_id: ${{ github.event.workflow_run.id }}
          if_no_artifact_found: fail
      - name: Verify downloaded artifacts
        run: |
          echo "Contents of current directory:"
          ls -la
          echo "Contents of apps/docs/build:"
          ls -la ./apps/docs/build || echo "Build directory not found"
      - name: Deploy Docs
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY_PRIVATE }}
          publish_dir: ./apps/docs/build
          external_repository: hades-ts/hades-ts.github.io
          publish_branch: main
          enable_jekyll: false
      - name: Kill SSH Agent
        run: killall ssh-agent || true 